jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
orbs:
  node: 'circleci/node@4.7.0'
version: 2.1
workflows:
  build:
    jobs:
      - lint
