version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  lint:
    executor: node/default
    steps:
      - node/install:
          install-npm: false 
          install-yarn: true 
          lts: true
      - checkout
      - run: yarn install
      - run: yarn lint
workflows:
  build:
    jobs:
      - lint
